### ISSUE TITLE
thoughts on URL being callable without `new`

### ISSUE THREAD

**Issue by davidmarkclements** [jasnell/proposal-url#2]
is 

```js
const base = URL('http://example.org/foo');
const url = URL('bar', base);
```

Acceptable?

This would be in line with some other native JS constructors, like `Error`

**Comment by jasnell** [comment]
This is governed by the WHATWG spec. That's where it would need to be proposed.
https://github.com/whatwg/url

**Comment by davidmarkclements** [comment]
I get it now - closing as not an issue for this

**Comment by stevenvachon** [comment]
This is still open, when perhaps it shouldn't be.
